apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cwpcompositeclusters.aws.platformref.crossplane.io
spec:
  #writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: aws.platformref.crossplane.io/v1alpha1
    kind: CwpCompositeCluster

  resources:

    - base:
        apiVersion: aws.platformref.crossplane.io/v1alpha1
        kind: CompositeNetwork
      patches:
        - fromFieldPath: spec.namespace
          toFieldPath: spec.namespace

        - fromFieldPath: spec.id
          toFieldPath: spec.id

        - fromFieldPath: spec.id
          toFieldPath: spec.clusterRef.id # Notice here  (== parnet spec.id)

        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.parameters.region

    - base:
        apiVersion: aws.platformref.crossplane.io/v1alpha1
        kind: CompositeEKS
      connectionDetails:
        - fromConnectionSecretKey: kubeconfig
      patches:
        - fromFieldPath: spec.namespace
          toFieldPath: spec.namespace

        - fromFieldPath: spec.id
          toFieldPath: metadata.annotations[crossplane.io/external-name]

        - fromFieldPath: spec.id
          toFieldPath: spec.id

        - fromFieldPath: spec.id
          toFieldPath: spec.networkRef.id # Notice here (== parnet spec.id)

        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.parameters.region

        - fromFieldPath: spec.parameters.eks.version
          toFieldPath: spec.parameters.version

        - fromFieldPath: spec.parameters.eks.scalingConfig
          toFieldPath: spec.parameters.nodes.scalingConfig

        - fromFieldPath: spec.parameters.eks.instanceType
          toFieldPath: spec.parameters.nodes.instanceType

        - fromFieldPath: spec.parameters.eks.diskSize
          toFieldPath: spec.parameters.nodes.diskSize


    - base:
        apiVersion: aws.platformref.crossplane.io/v1alpha1
        kind: Services

      patches:

        - fromFieldPath: spec.id
          toFieldPath: spec.providerConfigRef.name

        - fromFieldPath: spec.parameters.services.destination_namespace
          toFieldPath: spec.destination_namespace

          # aws_node_termination_handler
        - fromFieldPath: spec.parameters.services.aws_node_termination_handler.source_repo
          toFieldPath: spec.aws_node_termination_handler.source_repo
        - fromFieldPath: spec.parameters.services.aws_node_termination_handler.chart_name
          toFieldPath: spec.aws_node_termination_handler.chart_name
        - fromFieldPath: spec.parameters.services.aws_node_termination_handler.version
          toFieldPath: spec.aws_node_termination_handler.version
        #- fromFieldPath: spec.parameters.services.aws_node_termination_handler.values
        #  toFieldPath: spec.aws_node_termination_handler.values

          # cluster_autoscaler
        - fromFieldPath: spec.parameters.services.cluster_autoscaler.source_repo
          toFieldPath: spec.cluster_autoscaler.source_repo
        - fromFieldPath: spec.parameters.services.cluster_autoscaler.chart_name
          toFieldPath: spec.cluster_autoscaler.chart_name
        - fromFieldPath: spec.parameters.services.cluster_autoscaler.version
          toFieldPath: spec.cluster_autoscaler.version
        #- fromFieldPath: spec.parameters.services.cluster_autoscaler.values
        #  toFieldPath: spec.cluster_autoscaler.values

          # external_dns
        - fromFieldPath: spec.parameters.services.external_dns.source_repo
          toFieldPath: spec.external_dns.source_repo
        - fromFieldPath: spec.parameters.services.external_dns.chart_name
          toFieldPath: spec.external_dns.chart_name
        - fromFieldPath: spec.parameters.services.external_dns.version
          toFieldPath: spec.external_dns.version
        #- fromFieldPath: spec.parameters.services.external_dns.values
        #  toFieldPath: spec.external_dns.values

          # cert_manager
        - fromFieldPath: spec.parameters.services.cert_manager.source_repo
          toFieldPath: spec.cert_manager.source_repo
        - fromFieldPath: spec.parameters.services.cert_manager.chart_name
          toFieldPath: spec.cert_manager.chart_name
        - fromFieldPath: spec.parameters.services.cert_manager.version
          toFieldPath: spec.cert_manager.version
        #- fromFieldPath: spec.parameters.services.cert_manager.values
        #  toFieldPath: spec.cert_manager.values

          # ingress_nginx
        - fromFieldPath: spec.parameters.services.ingress_nginx.source_repo
          toFieldPath: spec.ingress_nginx.source_repo
        - fromFieldPath: spec.parameters.services.ingress_nginx.chart_name
          toFieldPath: spec.ingress_nginx.chart_name
        - fromFieldPath: spec.parameters.services.ingress_nginx.version
          toFieldPath: spec.ingress_nginx.version
        #- fromFieldPath: spec.parameters.services.ingress_nginx.values
        #  toFieldPath: spec.ingress_nginx.values

          # vouch
        - fromFieldPath: spec.parameters.services.vouch.source_repo
          toFieldPath: spec.vouch.source_repo
        - fromFieldPath: spec.parameters.services.vouch.chart_name
          toFieldPath: spec.vouch.chart_name
        - fromFieldPath: spec.parameters.services.vouch.version
          toFieldPath: spec.vouch.version
        #- fromFieldPath: spec.parameters.services.vouch.values
        #  toFieldPath: spec.vouch.values

          # kubernetes_external_secrets
        - fromFieldPath: spec.parameters.services.kubernetes_external_secrets.source_repo
          toFieldPath: spec.kubernetes_external_secrets.source_repo
        - fromFieldPath: spec.parameters.services.kubernetes_external_secrets.chart_name
          toFieldPath: spec.kubernetes_external_secrets.chart_name
        - fromFieldPath: spec.parameters.services.kubernetes_external_secrets.version
          toFieldPath: spec.kubernetes_external_secrets.version
        #- fromFieldPath: spec.parameters.services.kubernetes_external_secrets.values
        #  toFieldPath: spec.kubernetes_external_secrets.values

          # prometheus
        - fromFieldPath: spec.parameters.services.prometheus.source_repo
          toFieldPath: spec.prometheus.source_repo
        - fromFieldPath: spec.parameters.services.prometheus.chart_name
          toFieldPath: spec.prometheus.chart_name
        - fromFieldPath: spec.parameters.services.prometheus.version
          toFieldPath: spec.prometheus.version
        #- fromFieldPath: spec.parameters.services.prometheus.values
        #  toFieldPath: spec.prometheus.values

          # velero
        - fromFieldPath: spec.parameters.services.velero.source_repo
          toFieldPath: spec.velero.source_repo
        - fromFieldPath: spec.parameters.services.velero.chart_name
          toFieldPath: spec.velero.chart_name
        - fromFieldPath: spec.parameters.services.velero.version
          toFieldPath: spec.velero.version
        #- fromFieldPath: spec.parameters.services.velero.values
        #  toFieldPath: spec.velero.values
